function [out1,out2] = dotJa_2dofs(in1,in2,in3,in4)
%DOTJA_2DOFS
%    [OUT1,OUT2] = DOTJA_2DOFS(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Apr-2023 12:32:52

a1 = in3(3,:);
a2 = in3(6,:);
alpha1 = in3(1,:);
d2 = in3(5,:);
dotq1 = in2(1,:);
dotq2 = in2(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
rpy1_2 = in4(4,:);
rpy2_2 = in4(5,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = cos(q2);
t5 = cos(alpha1);
t6 = sin(q2);
t7 = sin(alpha1);
t8 = a2.*dotq2.*t3.*t6;
t9 = a2.*dotq1.*t3.*t5.*t6;
t10 = d2.*dotq1.*t2.*t7;
t11 = d2.*t5;
t12 = a2.*t6.*t7;
t13 = t11+t12;
t14 = t7.^2;
t15 = a2.*dotq1.*t3.*t4;
t16 = a2.*dotq2.*t2.*t6;
t17 = a2.*dotq1.*t2.*t5.*t6;
t18 = a2.*dotq2.*t3.*t4.*t5;
t19 = -t10+t15+t16+t17+t18;
t20 = a2.*dotq1.*t2.*t4;
t21 = d2.*dotq1.*t3.*t7;
t22 = a2.*dotq2.*t2.*t4.*t5;
t23 = -t8-t9+t20+t21+t22;
t24 = cos(rpy1_2);
t25 = cos(rpy2_2);
t26 = sin(rpy1_2);
t27 = t24.^2;
t28 = t26.^2;
t29 = t25.*t27;
t30 = t25.*t28;
t31 = t29+t30;
t32 = 1.0./t31;
out1 = reshape([t8+t9-a1.*dotq1.*t2-a2.*dotq1.*t2.*t4-d2.*dotq1.*t3.*t7-a2.*dotq2.*t2.*t4.*t5,t10-a1.*dotq1.*t3-a2.*dotq1.*t3.*t4-a2.*dotq2.*t2.*t6-a2.*dotq1.*t2.*t5.*t6-a2.*dotq2.*t3.*t4.*t5,0.0,0.0,0.0,0.0,-t5.*t23+dotq1.*t3.*t7.*t13-a2.*dotq2.*t2.*t4.*t14,-t5.*t19-dotq1.*t2.*t7.*t13-a2.*dotq2.*t3.*t4.*t14,-t2.*t7.*t19+t3.*t7.*t23+dotq1.*t2.*t7.*(a2.*t3.*t4-d2.*t2.*t7+a2.*t2.*t5.*t6)-dotq1.*t3.*t7.*(a2.*t2.*t4+d2.*t3.*t7-a2.*t3.*t5.*t6),dotq1.*t2.*t7+dotq1.*t3.*t7.*t26.*t32.*sin(rpy2_2),(dotq1.*t3.*t7.*t24)./(t27+t28),-dotq1.*t3.*t7.*t26.*t32],[6,2]);
if nargout > 1
    out2 = reshape([-a1.*dotq1.*t2,-a1.*dotq1.*t3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,2]);
end
