function g_q = g_2dofs(in1,in2,in3,in4)
%G_2DOFS
%    G_Q = G_2DOFS(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Apr-2023 12:32:51

a1 = in3(3,:);
a2 = in3(6,:);
alpha1 = in3(1,:);
alpha2 = in3(4,:);
d2 = in3(5,:);
gravx = in2(1,:);
gravy = in2(2,:);
gravz = in2(3,:);
m1 = in4(1,:);
m2 = in4(11,:);
q1 = in1(1,:);
q2 = in1(2,:);
rc1x = in4(2,:);
rc1y = in4(3,:);
rc2x = in4(12,:);
rc1z = in4(4,:);
rc2y = in4(13,:);
rc2z = in4(14,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = sin(q2);
t5 = cos(alpha1);
t6 = cos(alpha2);
t7 = cos(q2);
t8 = sin(alpha1);
t9 = sin(alpha2);
t10 = a1.*t3;
t11 = a1.*t2;
g_q = [-gravx.*m2.*(t10+rc2x.*(t3.*t7+t2.*t4.*t5)-rc2y.*(t3.*t4.*t6+t2.*t8.*t9-t2.*t5.*t6.*t7)-rc2z.*(t2.*t6.*t8-t3.*t4.*t9+t2.*t5.*t7.*t9)+a2.*t3.*t7-d2.*t2.*t8+a2.*t2.*t4.*t5)+gravy.*m2.*(t11+rc2x.*(t2.*t7-t3.*t4.*t5)-rc2y.*(t2.*t4.*t6-t3.*t8.*t9+t3.*t5.*t6.*t7)+rc2z.*(t2.*t4.*t9+t3.*t6.*t8+t3.*t5.*t7.*t9)+a2.*t2.*t7+d2.*t3.*t8-a2.*t3.*t4.*t5)-gravx.*m1.*(t10+rc1x.*t3+rc1y.*t2.*t5-rc1z.*t2.*t8)+gravy.*m1.*(t11+rc1x.*t2-rc1y.*t3.*t5+rc1z.*t3.*t8);gravz.*m2.*(a2.*t7.*t8+rc2x.*t7.*t8-rc2y.*t4.*t6.*t8+rc2z.*t4.*t8.*t9)-gravx.*m2.*(rc2y.*(t2.*t6.*t7-t3.*t4.*t5.*t6)-rc2z.*(t2.*t7.*t9-t3.*t4.*t5.*t9)+rc2x.*(t2.*t4+t3.*t5.*t7)+a2.*t2.*t4+a2.*t3.*t5.*t7)-gravy.*m2.*(rc2y.*(t3.*t6.*t7+t2.*t4.*t5.*t6)-rc2z.*(t3.*t7.*t9+t2.*t4.*t5.*t9)+rc2x.*(t3.*t4-t2.*t5.*t7)+a2.*t3.*t4-a2.*t2.*t5.*t7)];
