function [out1,out2] = H_2dofs(in1,in2)
%H_2DOFS
%    [OUT1,OUT2] = H_2DOFS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Apr-2023 12:32:51

a1 = in2(3,:);
a2 = in2(6,:);
alpha1 = in2(1,:);
alpha2 = in2(4,:);
d1 = in2(2,:);
d2 = in2(5,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = cos(q1);
t3 = sin(q2);
t4 = sin(q1);
t5 = cos(alpha1);
t6 = cos(alpha2);
t7 = cos(q2);
t8 = sin(alpha1);
t9 = sin(alpha2);
t10 = a1.*t2;
t11 = a1.*t4;
out1 = reshape([t2.*t7-t3.*t4.*t5,t4.*t7+t2.*t3.*t5,t3.*t8,0.0,-t2.*t3.*t6+t4.*t8.*t9-t4.*t5.*t6.*t7,-t3.*t4.*t6-t2.*t8.*t9+t2.*t5.*t6.*t7,t5.*t9+t6.*t7.*t8,0.0,t2.*t3.*t9+t4.*t6.*t8+t4.*t5.*t7.*t9,-t2.*t6.*t8+t3.*t4.*t9-t2.*t5.*t7.*t9,t5.*t6-t7.*t8.*t9,0.0,t10+a2.*t2.*t7+d2.*t4.*t8-a2.*t3.*t4.*t5,t11+a2.*t4.*t7-d2.*t2.*t8+a2.*t2.*t3.*t5,d1+d2.*t5+a2.*t3.*t8,1.0],[4,4]);
if nargout > 1
    out2 = reshape([t2,t4,0.0,0.0,-t4.*t5,t2.*t5,t8,0.0,t4.*t8,-t2.*t8,t5,0.0,t10,t11,d1,1.0],[4,4]);
end
