function [out1,out2] = Ja_2dofs(in1,in2,in3)
%JA_2DOFS
%    [OUT1,OUT2] = JA_2DOFS(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Apr-2023 12:32:51

a1 = in2(3,:);
a2 = in2(6,:);
alpha1 = in2(1,:);
d2 = in2(5,:);
q1 = in1(1,:);
q2 = in1(2,:);
rpy1_1 = in3(1,:);
rpy1_2 = in3(4,:);
rpy2_1 = in3(2,:);
rpy2_2 = in3(5,:);
t2 = sin(q1);
t3 = cos(q1);
t4 = cos(alpha1);
t5 = sin(alpha1);
t6 = d2.*t3.*t5;
t7 = cos(q2);
t8 = sin(q2);
t9 = a2.*t3.*t7;
t10 = d2.*t2.*t5;
t11 = d2.*t4;
t12 = a2.*t5.*t8;
t13 = t11+t12;
t14 = t9+t10-a2.*t2.*t4.*t8;
t15 = a2.*t2.*t7;
t16 = a2.*t3.*t4.*t8;
t17 = -t6+t15+t16;
t18 = cos(rpy1_2);
t19 = cos(rpy2_2);
t20 = sin(rpy1_2);
t21 = sin(rpy2_2);
t22 = t18.^2;
t23 = t19.*t22;
t24 = t20.^2;
t25 = t19.*t24;
t26 = t23+t25;
t27 = 1.0./t26;
t28 = t22+t24;
t29 = 1.0./t28;
t30 = a1.*t3;
out1 = reshape([t6-a1.*t2-a2.*t2.*t7-a2.*t3.*t4.*t8,t9+t10+t30-a2.*t2.*t4.*t8,0.0,-t18.*t21.*t27,t20.*t29,t18.*t27,-t4.*t17-t3.*t5.*t13,t4.*t14-t2.*t5.*t13,t3.*t5.*t14+t2.*t5.*t17,t2.*t5-t4.*t18.*t21.*t27-t3.*t5.*t20.*t21.*t27,t4.*t20.*t29-t3.*t5.*t18.*t29,t4.*t18.*t27+t3.*t5.*t20.*t27],[6,2]);
if nargout > 1
    t31 = cos(rpy1_1);
    t32 = cos(rpy2_1);
    t33 = sin(rpy1_1);
    t34 = t31.^2;
    t35 = t33.^2;
    t36 = t32.*t34;
    t37 = t32.*t35;
    t38 = t36+t37;
    t39 = 1.0./t38;
    out2 = reshape([-a1.*t2,t30,0.0,-t31.*t39.*sin(rpy2_1),t33./(t34+t35),t31.*t39,0.0,0.0,0.0,0.0,0.0,0.0],[6,2]);
end
