function [out1,out2] = Jg_2dofs(in1,in2)
%JG_2DOFS
%    [OUT1,OUT2] = JG_2DOFS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    21-Apr-2023 12:32:51

a1 = in2(3,:);
a2 = in2(6,:);
alpha1 = in2(1,:);
d2 = in2(5,:);
q1 = in1(1,:);
q2 = in1(2,:);
t2 = sin(q1);
t3 = cos(q1);
t4 = cos(alpha1);
t5 = sin(alpha1);
t6 = d2.*t3.*t5;
t7 = cos(q2);
t8 = sin(q2);
t9 = a2.*t3.*t7;
t10 = d2.*t2.*t5;
t11 = d2.*t4;
t12 = a2.*t5.*t8;
t13 = t11+t12;
t14 = t9+t10-a2.*t2.*t4.*t8;
t15 = a2.*t2.*t7;
t16 = a2.*t3.*t4.*t8;
t17 = -t6+t15+t16;
t18 = a1.*t3;
out1 = reshape([t6-a1.*t2-a2.*t2.*t7-a2.*t3.*t4.*t8,t9+t10+t18-a2.*t2.*t4.*t8,0.0,0.0,0.0,1.0,-t4.*t17-t3.*t5.*t13,t4.*t14-t2.*t5.*t13,t3.*t5.*t14+t2.*t5.*t17,t2.*t5,-t3.*t5,t4],[6,2]);
if nargout > 1
    out2 = reshape([-a1.*t2,t18,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,2]);
end
