function T2Eq = GravityCompT2(Fdx,Fdy,d2,g,l1,l2,m2,th1,th2,thdot1)
%GravityCompT2
%    T2Eq = GravityCompT2(Fdx,Fdy,D2,G,L1,L2,M2,TH1,TH2,THDOT1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023-12-04 11:02:00

t2 = th1+th2;
t3 = cos(t2);
T2Eq = -Fdy.*l2.*t3+Fdx.*l2.*sin(t2)+d2.*g.*m2.*t3+d2.*l1.*m2.*thdot1.^2.*sin(th2);
end
