function Ta = ImpedenceControl(Kd,Kp,l1,l2,th1,th2,thdot1,thdot2,xdott,xt,ydott,yt)
%ImpedenceControl
%    Ta = ImpedenceControl(Kd,Kp,L1,L2,TH1,TH2,THDOT1,THDOT2,XDOTT,XT,YDOTT,YT)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2023-12-04 11:02:00

t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t9 = -xt;
t10 = -ydott;
t11 = -yt;
t5 = l1.*t2;
t6 = cos(t4);
t7 = l1.*t3;
t8 = sin(t4);
t12 = l2.*t6;
t13 = l2.*t8;
t14 = t12.*thdot2;
t15 = t13.*thdot2;
t16 = t5+t12;
t17 = t7+t13;
t18 = t16.*thdot1;
t19 = t17.*thdot1;
t20 = t9+t16;
t21 = t11+t17;
t22 = Kp.*t21;
t23 = Kp.*t20;
t25 = t15+t19+xdott;
t27 = t10+t14+t18;
t26 = Kd.*t25;
t28 = Kd.*t27;
t30 = t22+t28;
Ta = [-t16.*t30+t17.*(t23-t26);-t12.*t30+t13.*(t23-t26)];
end
